# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        doctrine_http_login:
            entity:
                class: AppBundle:User
                
        doctrine_api_key:
            entity:
                class: AppBundle:User
                property: apiKey

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)/
            security: false
            
        http-logging:
            anonymous: ~

            http_basic: ~
            
            provider: doctrine_http_login
            
            pattern: ^/basic-auth
            
            logout:
                path: logout_path
            
        api_key:
            guard:
                authenticators:
                    - AppBundle\Security\ApiKeyAuthenticator
            
            provider: doctrine_api_key
            
            
    access_control:
        - { path: ^/basic-auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
            